name: API_KEY_Automation

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11' # or your desired Java version

      - name: Load API Key
        env:
          API_KEY: ${{ secrets.api_key }}
        run: echo "API_KEY=${API_KEY}" >> $GITHUB_ENV

      - name: Build and test
        run: ./gradlew assembleDebug # or your build command
