name: Build and Test Android

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Load local.properties
        env:
          LOCAL_PROPERTIES_CONTENTS: ${{ secrets.LOCAL_PROPERTIES_CONTENTS }}
        run: |
          echo %LOCAL_PROPERTIES_CONTENTS% | base64 -d > local.properties

      - name: Build and test
        run: .\gradlew build
