name: Build and Test Android

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Load secrete.properties
        env:
          LOCAL_PROPERTIES_CONTENTS: ${{ secrets.LOCAL_PROPERTIES_CONTENTS }}
        run: |
          echo "Decoding and writing secrete.properties file..."
          echo $LOCAL_PROPERTIES_CONTENTS | base64 --decode > secrete.properties
          echo "Contents of local.properties:"
          cat local.properties

      - name: Debug LOCAL_PROPERTIES_CONTENTS
        run: echo $LOCAL_PROPERTIES_CONTENTS

      - name: Build and test
        run: ./gradlew build
