name: Build and Test Android

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Create secrete.properties
        run: |
          echo "my_property=value123" > secrete.properties
          echo "another_property=anotherValue456" >> secrete.properties

      - name: Load secrete.properties
        env:
          LOCAL_PROPERTIES_PATH: secrete.properties
        run: |
          echo "Contents of secrete.properties:"
          cat $LOCAL_PROPERTIES_PATH

      - name: Build and test
        run: ./gradlew build
